import { Router, type IRouter } from "express";
import healthRouter from "./health";
import homeRouter from "./home";
import propertiesRouter from "./properties";
import availabilityRouter from "./availability";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import wishlistRouter from "./wishlist";
import adminRouter from "./admin";
import cmsRouter from "./cms";
import meRouter from "./me";
import partnerRouter from "./partner";
import customerLoginRouter from "./customerLogin";
import employeeRouter from "./employee";
import storageRouter from "./storage";
import destinationsRouter from "./destinations";
import assistantRouter from "./assistant";
import agentRouter from "./agent";
import marketingRouter from "./marketing";
import propertyCategoriesRouter from "./propertyCategories";
import billingRouter from "./billing";
import postalDirectoryRouter from "./postalDirectory";
import propertyDocumentsRouter from "./propertyDocuments";
import razorpayRouter from "./razorpay";

const router: IRouter = Router();

router.use(healthRouter);
router.use(homeRouter);
router.use(cmsRouter);
router.use(availabilityRouter);
router.use(reviewsRouter);
router.use(propertiesRouter);
router.use(bookingsRouter);
router.use(wishlistRouter);
router.use(meRouter);
router.use(partnerRouter);
router.use(customerLoginRouter);
router.use(employeeRouter);
router.use(adminRouter);
router.use(storageRouter);
router.use(destinationsRouter);
router.use(assistantRouter);
router.use(agentRouter);
router.use(marketingRouter);
router.use(propertyCategoriesRouter);
router.use(billingRouter);
  router.use(postalDirectoryRouter);
  router.use(propertyDocumentsRouter);
  router.use(razorpayRouter);

export default router;
